/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface DeviceDetails {
  'ramGb' : bigint,
  'screenSizeInches' : bigint,
  'deviceModel' : string,
}
export interface PaymentRequest {
  'status' : PaymentRequestStatus,
  'createdAt' : bigint,
  'user' : Principal,
  'paymentReference' : string,
}
export type PaymentRequestStatus = { 'pending' : null } |
  { 'approved' : null };
export interface SensitivitySettings {
  'generalSensitivity' : bigint,
  'noScopeSensitivity' : bigint,
  'redDotSensitivity' : bigint,
  'scope2xSensitivity' : bigint,
  'scope4xSensitivity' : bigint,
  'awmScopeSensitivity' : bigint,
  'fireButtonSize' : bigint,
  'gameBoosterTips' : string,
  'deviceDetails' : DeviceDetails,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePaymentRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaymentRequest' : ActorMethod<[bigint], PaymentRequest>,
  'getSensitivitySettings' : ActorMethod<[], SensitivitySettings>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'revokeAccess' : ActorMethod<[Principal], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitDeviceDetails' : ActorMethod<[DeviceDetails], SensitivitySettings>,
  'submitPaymentRequest' : ActorMethod<[string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];