/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'status' : PaymentRequestStatus,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'paymentReference' : IDL.Text,
});
export const DeviceDetails = IDL.Record({
  'ramGb' : IDL.Nat,
  'screenSizeInches' : IDL.Nat,
  'deviceModel' : IDL.Text,
});
export const SensitivitySettings = IDL.Record({
  'dpi' : IDL.Nat,
  'deviceDetails' : DeviceDetails,
  'gameBoosterTips' : IDL.Text,
  'sensitivity' : IDL.Nat,
  'fireButtonSize' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePaymentRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaymentRequest' : IDL.Func([IDL.Nat], [PaymentRequest], ['query']),
  'getSensitivitySettings' : IDL.Func([], [SensitivitySettings], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'requestApproval' : IDL.Func([], [], []),
  'revokeAccess' : IDL.Func([IDL.Principal], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'submitDeviceDetails' : IDL.Func([DeviceDetails], [SensitivitySettings], []),
  'submitPaymentRequest' : IDL.Func([IDL.Text], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
  });
  const PaymentRequest = IDL.Record({
    'status' : PaymentRequestStatus,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'paymentReference' : IDL.Text,
  });
  const DeviceDetails = IDL.Record({
    'ramGb' : IDL.Nat,
    'screenSizeInches' : IDL.Nat,
    'deviceModel' : IDL.Text,
  });
  const SensitivitySettings = IDL.Record({
    'dpi' : IDL.Nat,
    'deviceDetails' : DeviceDetails,
    'gameBoosterTips' : IDL.Text,
    'sensitivity' : IDL.Nat,
    'fireButtonSize' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePaymentRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaymentRequest' : IDL.Func([IDL.Nat], [PaymentRequest], ['query']),
    'getSensitivitySettings' : IDL.Func([], [SensitivitySettings], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'requestApproval' : IDL.Func([], [], []),
    'revokeAccess' : IDL.Func([IDL.Principal], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'submitDeviceDetails' : IDL.Func(
        [DeviceDetails],
        [SensitivitySettings],
        [],
      ),
    'submitPaymentRequest' : IDL.Func([IDL.Text], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };